apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml

namespace: openclaw-operator

helmCharts:
- name: openclaw-operator
  releaseName: openclaw-operator
  version: 0.30.0
  repo: oci://ghcr.io/openclaw-rocks/charts
  namespace: openclaw-operator
  includeCRDs: true
  valuesFile: ./resources/values.yaml
