apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/volume.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/funkwhale-secrets.yaml

namespace: funkwhale
