apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./resources/ingress.yaml
- ./resources/volume.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-generator
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secrets/funkwhale-secrets.yaml

namespace: funkwhale
