---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-200-route
  annotations:
    external-dns.alpha.kubernetes.io/target: "envoy.k8s.305-1700.tdude.co"
spec:
  parentRefs:
  - name: envoy-gateway # Reference your Gateway resource
    namespace: envoy-gateway  # Replace with the namespace of your Gateway
  hostnames:
  - dummy.305-1700.tdude.co
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: http-200-svc
      namespace: envoy-gateway
      port: 80 # Match the "https" port specified in your service
---
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: dummy-listeners
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # Reference the central Gateway
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
  listeners:
    - name: dummy-https
      hostname: dummy.305-1700.tdude.co
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        # The secret where cert-manager will store the cert
        certificateRefs:
          - name: app-tls-secret
            group: ""
            kind: Secret