apiVersion: v1
kind: Secret
metadata:
    name: postgres-config
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    POSTGRESQL_HOSTNAME: ENC[AES256_GCM,data:aqir+a7dkUDWHBR7BQN0ENw9dbUs,iv:3L2x1STBXev89MIabLjK53xXuJrmDTNhKuKMifacBFw=,tag:vXPO/IRwxzZe097RQJsLQg==,type:str]
    POSTGRESQL_DATABASE: ENC[AES256_GCM,data:8sqMpfX1Bxpv,iv:u+YvBouC9f77DgWHFqk3t5dE9qa4HrWDLnc4ex9q6k4=,tag:lqi7b/SUfYwN4OkuPttUQQ==,type:str]
    POSTGRESQL_USERNAME: ENC[AES256_GCM,data:PDz4OASHOPo2,iv:auOKWQQsTHde/5NTTifQvC/Tu8+HAUiFZR+IXc7LlQo=,tag:lJds4Hu3A6oD1XO4yl404A==,type:str]
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:76oPVnT5el+XbrWxV/l4zuuaRj7YTeSWXtpKgiwTkdc=,iv:53C+fmGJnGUSfhaMZN9NP/RFP7Qn8qq4FjRTUzzwkw0=,tag:aGgll28mzR47eCC38QktRQ==,type:str]
sops:
    lastmodified: "2026-02-23T03:26:01Z"
    mac: ENC[AES256_GCM,data:Gahg77+AeTijSHw0RY76kayQVe+m3VFrxEPEA1x+jyWVE844c/6z6HGzx0LSWiIhM7GNaGDgC602JUvSb7ZIUa1UhLyhqCZK2mpuNU41aqMvXjzRdxgTQT0pBUyUvlgJyGbRYIqpXXc2d0rM2ikiiDeUT9Zto8agj4NxzzYUt8U=,iv:4HiVyOE0Vn6FaYaNOM723OurzZ5z5hWot1i4qRCtCys=,tag:jQfREs2aqPOxKfMNL6fBiA==,type:str]
    pgp:
        - created_at: "2026-02-23T03:26:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ/9FUqTpcJvjQmtI1Y40BAs0mipMnyGraB2CUd/yxJAMZZz
            NgIxAx/KuMyAz9uOFOenaK9sMNcpt3Uqo5XuJB3IoLvkPW81F95ejS2yOPKMdT4B
            0lAYnybmQ2YkhdGXlRxdkKtxsYxrWGsnInlDkNznRPVlbPGQGa6prnSGsbtF8PwL
            I3EQJN+TH+GlWRGbTxfPBw2+JxD5r0MvHm32kndzipDzjLmHBQys3ZLuBg8z3I0r
            mtBY/W/zj5IH8UlFFqPLVP10Iqc3N6zhXn1bzHu5BoISH3p0gWMo0y5IKe+qUiDD
            CIG+jdhoDhD/qfQ8AiaVdTmA4xwyJE29Cafngg1Md2ImidGTwEEOVDdBiU3p0GR9
            ymUB1pO/gJAKdlbYb4XeYeVwQfVrQR4xt49ZbNzveuoW/rIQna7xildq3KQYjOyz
            g5tKJTZvg5uBB/OKS04rtr8L01kb0zMItj+CNOFUeBGBAN/0bVRBQBJYCnFIKJTW
            v5UA7eNdjf+k9/Bt//tKy14SZrpFl4BRN43FKE+sIpZoYHQGv8GuUepo3YygggDT
            L3nwPPwqlFpGTD9lcwGl5QKDrW/0T8HiCoVQV3zYEXb5W0JHfGEGXnQGrH5orYwA
            jbLSBm8hTpVyJTvexvZ2ikS2oOfwcinY1ndd34Cfr/iQImHFfS7jfSTQsFhyei/S
            XgFTGzqxW57TTpE7SvuRHObrJmwQ5PwgED+kpUFLXUPUS/Kcut6lHm0mpUv4f11w
            ur7d+tCSahKawpvL8u5vAaZ6Z7JrG0DTGcjWQk2vcZEv1VeMES97u5VDLxa9TAU=
            =2bjE
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-02-23T03:26:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/+PnXvNDBx/2IwTjBUthtR1jXgLm2O+0V/Aewyy6Y439vt
            5Ujmcei1bVMsfhFW06az0jkqz/RoAjB3ChYEXribSqDgToZqjNxONPiMcTsiWvJs
            Yn9lWySkNLKAYbxuwnvN32Rku84/dlX8n/kAfXahpauNrL4GpBiakia+8VzVJgna
            hpLmhQuY+fj0hRyGFWc6adEIwPvuroElX287ajN0DQflCgWOgZWBSHLNGbBHictC
            3NLp+YQQTuB9pL1wNbDAfbMXgRut76/ZC7iFon7IGnWMrhH1iNZ5nbYC6pG9j4HJ
            fT721WMBryZGvD81ha2u1mtdLNUjKjU3/szxxTY33qttif9QGelJdXGyA2aFyDWK
            GxZBrGmvmwSra4c77iaxBjNMMJakFtGK04mhXrlMzu4sf3YXm+hCpTVbURIm5y1K
            QJVAleiwB/rt7o4OMujoljiCeBz4Q01jJjodICAlfO6AUsj958HOYBJLLQtJ1vLO
            gXxUtcD1XjaPPAD9cd5lAf3TFbyy+Sy7zc6d9k6KK4AANYaDvM3qEzVuSfwyN7Js
            L8anQpaaWr3BbsQgrLJJ2m9iJY5exsz0fHRp+TvJTWgYnWhlOCfuq2ITEXWn0iVB
            oa0Kk1XoYC4ra7aBcngTHAnVOJ/z/cYVzvOi9Beo15FAR3KdG3bqyf5x1715+lbS
            XgFYc7NkrdauwxHIKZPVm0e1cv+26B4qhXyNDyG5yXc6ATA1t3QUb0eN1ao9DKLX
            Lowoz2sG/I9qj1Ot1FnYJtVFyG7+txJbv6vla9uYOo1l9hxKHnpxKYNtyUBueDY=
            =19jG
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
stringData:
    username: ENC[AES256_GCM,data:Z35u5jnJD9IN,iv:74DZAu0N/Vf4Vj/1GWfTF77j0Oucoywm49N7jvpv8eM=,tag:2IUx17z8sfQyytAU1ROFOQ==,type:str]
    password: ENC[AES256_GCM,data:5CtModYIyX3147Yh+HGuRsdiJ4GFZfXerLchfE/OqHE=,iv:4sxErru5UDZrjufELGpsExv57mZ77aipOB9lx2J69MQ=,tag:ufGHJ3e4y1BK6I7faRRaew==,type:str]
type: kubernetes.io/basic-auth
sops:
    lastmodified: "2026-02-23T03:26:01Z"
    mac: ENC[AES256_GCM,data:Gahg77+AeTijSHw0RY76kayQVe+m3VFrxEPEA1x+jyWVE844c/6z6HGzx0LSWiIhM7GNaGDgC602JUvSb7ZIUa1UhLyhqCZK2mpuNU41aqMvXjzRdxgTQT0pBUyUvlgJyGbRYIqpXXc2d0rM2ikiiDeUT9Zto8agj4NxzzYUt8U=,iv:4HiVyOE0Vn6FaYaNOM723OurzZ5z5hWot1i4qRCtCys=,tag:jQfREs2aqPOxKfMNL6fBiA==,type:str]
    pgp:
        - created_at: "2026-02-23T03:26:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5mBKGEIMocYAQ/9FUqTpcJvjQmtI1Y40BAs0mipMnyGraB2CUd/yxJAMZZz
            NgIxAx/KuMyAz9uOFOenaK9sMNcpt3Uqo5XuJB3IoLvkPW81F95ejS2yOPKMdT4B
            0lAYnybmQ2YkhdGXlRxdkKtxsYxrWGsnInlDkNznRPVlbPGQGa6prnSGsbtF8PwL
            I3EQJN+TH+GlWRGbTxfPBw2+JxD5r0MvHm32kndzipDzjLmHBQys3ZLuBg8z3I0r
            mtBY/W/zj5IH8UlFFqPLVP10Iqc3N6zhXn1bzHu5BoISH3p0gWMo0y5IKe+qUiDD
            CIG+jdhoDhD/qfQ8AiaVdTmA4xwyJE29Cafngg1Md2ImidGTwEEOVDdBiU3p0GR9
            ymUB1pO/gJAKdlbYb4XeYeVwQfVrQR4xt49ZbNzveuoW/rIQna7xildq3KQYjOyz
            g5tKJTZvg5uBB/OKS04rtr8L01kb0zMItj+CNOFUeBGBAN/0bVRBQBJYCnFIKJTW
            v5UA7eNdjf+k9/Bt//tKy14SZrpFl4BRN43FKE+sIpZoYHQGv8GuUepo3YygggDT
            L3nwPPwqlFpGTD9lcwGl5QKDrW/0T8HiCoVQV3zYEXb5W0JHfGEGXnQGrH5orYwA
            jbLSBm8hTpVyJTvexvZ2ikS2oOfwcinY1ndd34Cfr/iQImHFfS7jfSTQsFhyei/S
            XgFTGzqxW57TTpE7SvuRHObrJmwQ5PwgED+kpUFLXUPUS/Kcut6lHm0mpUv4f11w
            ur7d+tCSahKawpvL8u5vAaZ6Z7JrG0DTGcjWQk2vcZEv1VeMES97u5VDLxa9TAU=
            =2bjE
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-02-23T03:26:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0LGYlOQPTf9AQ/+PnXvNDBx/2IwTjBUthtR1jXgLm2O+0V/Aewyy6Y439vt
            5Ujmcei1bVMsfhFW06az0jkqz/RoAjB3ChYEXribSqDgToZqjNxONPiMcTsiWvJs
            Yn9lWySkNLKAYbxuwnvN32Rku84/dlX8n/kAfXahpauNrL4GpBiakia+8VzVJgna
            hpLmhQuY+fj0hRyGFWc6adEIwPvuroElX287ajN0DQflCgWOgZWBSHLNGbBHictC
            3NLp+YQQTuB9pL1wNbDAfbMXgRut76/ZC7iFon7IGnWMrhH1iNZ5nbYC6pG9j4HJ
            fT721WMBryZGvD81ha2u1mtdLNUjKjU3/szxxTY33qttif9QGelJdXGyA2aFyDWK
            GxZBrGmvmwSra4c77iaxBjNMMJakFtGK04mhXrlMzu4sf3YXm+hCpTVbURIm5y1K
            QJVAleiwB/rt7o4OMujoljiCeBz4Q01jJjodICAlfO6AUsj958HOYBJLLQtJ1vLO
            gXxUtcD1XjaPPAD9cd5lAf3TFbyy+Sy7zc6d9k6KK4AANYaDvM3qEzVuSfwyN7Js
            L8anQpaaWr3BbsQgrLJJ2m9iJY5exsz0fHRp+TvJTWgYnWhlOCfuq2ITEXWn0iVB
            oa0Kk1XoYC4ra7aBcngTHAnVOJ/z/cYVzvOi9Beo15FAR3KdG3bqyf5x1715+lbS
            XgFYc7NkrdauwxHIKZPVm0e1cv+26B4qhXyNDyG5yXc6ATA1t3QUb0eN1ao9DKLX
            Lowoz2sG/I9qj1Ot1FnYJtVFyG7+txJbv6vla9uYOo1l9hxKHnpxKYNtyUBueDY=
            =19jG
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
