workload:
  main:
    strategy: Recreate
    podSpec:
      containers:
        main:
          resources:
            requests:
              devic.es/zwave: 1
            limits:
              devic.es/zwave: 1

persistence:
  config:
    enabled: true

portal:
  open:
    enabled: true

securityContext:
  container:
    runAsGroup: 27