= DNS
// Only set imagesdir if the file hasn't been included by one with a different imagesdir
ifndef::imagesdir[:imagesdir: ../.gitlab/images]

== Overview

[.text-justify]
I try to keep all configuration related to the deployment of a particular "application" or "unit" together. This is why, for example, many deployments in the `k8s/apps` folder have their own OpenTofu configurations for DNS and other cloud resources. For underlying infrastructure, this is less obvious so the `dns` folder is a collection of DNS zones and records that don't exactly fit with a particular project and are all applied in one collection of OpenTofu.

== Zones

[.text-justify]
The following zones, including their DNSSEC configuration are managed by this collection:

- as208914.net
- nerdsin.space
- shitsta.in
- tdude.co

=== ☁️ Making changes

These DNS zones are managed by Cloudflare and changes are performed with OpenTofu using the official Cloudflare provider. State is stored in a MinIO bucket on `spitfire`.

.Procedure to apply DNS changes
[%collapsible]
====
[source,console]
----
cd dns/
tofu init   # only needed on first run or after provider version changes
tofu plan   # review the planned changes
tofu apply  # apply the changes to Cloudflare
----
====
