apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.30/releases/cnpg-1.30.0.yaml
- https://github.com/cloudnative-pg/artifacts//image-catalogs-extensions?ref=main

namespace: cnpg
