apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml
- ./resources/openclawinstance.yaml
- ./resources/nginx-config.yaml
- ./resources/public-basic-auth-middleware.yaml
- ./resources/public-ingress.yaml

namespace: claw
