apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: descheduler
  namespace: descheduler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: descheduler
      app.kubernetes.io/instance: descheduler
