apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml

namespace: cert-manager

helmCharts:
- name: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  version: v1.20.0-alpha.1
  repo: https://charts.jetstack.io
  namespace: cert-manager
  valuesInline:
    global:
      leaderElection:
        namespace: cert-manager
    installCRDs: true
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
      featureGates:
        # We stay on v1.20.0-alpha.1 to retain XListenerSet support since
        # envoy-gateway does not yet support Gateway API v1.5.0-0.rc1
        # which moves ListernerSets out of experimental, gotta wait that out.
        EnableGatewayAPIXListenerSet: true
        # becomes EnableGatewayAPIListenerSet as of cert-manager v1.20.0-beta.0
        # EnableGatewayAPIListenerSet: true