apiVersion: v1
kind: Secret
metadata:
    name: openclaw-api-keys
type: Opaque
stringData:
    OPENCODE_API_KEY: ENC[AES256_GCM,data:WeCLTmXx77yPhliMATNdUnT8GxaH8qHYTcKRRJhoTzPEFU8wP8JWAGcQuavIfINQYxF9xGlKJykePf7wvoe41PlFUQ==,iv:VU6A294Ev5vznpG2DEobyjCR0JIGNF3JoIGmq1xctHg=,tag:4bzJbAjYmSt+WlpfGAyFeA==,type:str]
sops:
    lastmodified: "2026-03-21T02:24:51Z"
    mac: ENC[AES256_GCM,data:49IrcVz8eOuBtZuwVtdFE8y2XtDAQ1oN2XjwFD/M/f+UnxWuSdb1EhftJDUqWaD7uk0Zl4VIPSBqCWd6QkFWELgEOcIkYlyEkA5g94BqNQMJUQYaWjnVa31jUaL2zeO/W5bDlhPeCTpke5YGDYOOWMnHeIqxcDCUf6TtC+KzO3k=,iv:LgwxNjU464VJaQYwwjUziPbOAYWNfWdte3w6fx/v2Jg=,tag:jUyjDtNJPgijVhpUDRXwxg==,type:str]
    pgp:
        - created_at: "2026-03-21T02:24:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYAQ/9HeFVkGQscylEfJl4bhPiGLZ42yWssQVCAmR8opv1zkng
            Nb4OUUg6QD64SZWjDEatR+RkEMGULBCG3GDV0T24ol6VBm5tApIvNrngaYymCuQl
            J1STXOrmu9iHMpx5kU0I9sBupLcjSZD/47incL71YbE4oCpuh5+6mqzYHAmmVmvz
            Jlm/0ITGUPYCFwyq1tVFG1z+X3sm6aIwYgoeBZl2OUO/6q5or3FeXu9NGzVpcqIw
            Km/myjUKrGEeZ7fRkJOYNcrw0emJToEGM14h7RAgYD2uW0pcr3aFAIrrzAoEcMlM
            ghi6rUmMPryaSAG8/C6ie5gqGjF2G1cu08jMlpMv74C6C5PjekPSdvwzFgQZUv8s
            MpriOQOna0ILSN2ztbCvuu13W9ZKFEespipCptcbWR49J7x8m9349z6f1sv/wGP8
            9J8gfSEDHk+LJJhukck5YolLqxZee9wovyrKvPltnf27jSX6ST1GIVgcqCFErFv9
            /qaHnIyyX2muZ1s1cBCeDF1o+E288EzCdnJkVFTnYDDEcJld6qu0MZoSoAT3SpJQ
            foCtjYytDIrMgVwTjkEJNWY1oPfykchpLXlkOKXxlrDq/OAE7kGn/b9P4Oa7HDm5
            NdxUy6GLGdrCufr0rVn9bVtUJ77N/7o5xwCC0ymXw3qWSG2amvB4LzSWwERhCwbS
            UQEmuRllBecLZ/2UyAr2byZiPKmhKd/onbs7ZkD5fitfMKd2MzzjRWPfDyKEbXuI
            94kS/S+b9jIC04nXDBZx8jcZ2iwh3LglYOXSnOvjOQQDtQ==
            =XAzF
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-03-21T02:24:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9ARAAgLFLUeRYQ2kHmAGwxjuc3NszsiAJlDROtxlvcJy7TEy2
            DnFpYZi2K8c/Gm/D3ubmCRjUNQLFV/rpvedYm6dDmAyAYdb/H5zr3bR69f4dG3gV
            biDsF1CQvn04uG7iIBYGgH/UMsDlzLbyzObo8EnAjpR57dyhhCRTpWWPhmkXHJC3
            ZoHqkNIJnkFo0wzaj7BH+i2YdCcwFTF80XeA4GyA3gSVZgVlSaD7MMsS3+S0k4mf
            XWN34a71wlWdtB1PY/s53T5I0qPSaLxEF9CS2LHZlSpcMp4mwo1dnqHu5+zJmrkk
            prZv5G0Q5vUB7WWvJVNkCT5BoBMdVKlLwC7iOWdyWnJcAZHq6hMufS/BCRrgl3HN
            DSyvLLua6HMo9fDza3aSXP8Lim9UIX71HB0M2Xl++K9mNE0wtilJp//blKrmNhyh
            MVBcQlPInu/BOplXALhaRdBIvcuyFY1BU1vYfd7xgByzpc5kVR27UwjMFMOSzVSa
            +t4BWjm+jcmMHb2WuzAQ+BoH1mxE6IxSyQvZLhFMSDlZejoly8xn8uwcX+fgggZ9
            e3yy+sHR8/gvydIMJctqfb5DYzl+UffxKWO7R/vQ1+SUAqvDmIyCJgRdXkr74ZzK
            4+oq5XacvJ6p3YXn7lngJj4zfbDpxGKu7JNQOH4A9fun9mEw+r7hvZdh1Ubf9efS
            UQEL70C0FB7/yqC1fdLhKbkA0UPuIGI7sRz7LvHiMBUbeyrx8FcYX7y6+nqlHmMI
            rKjwX9trggeYwtVkS0Rc3FMCdSLBwLK8zyeTvnE9Qz412g==
            =XVEq
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
