apiVersion: v1
kind: Secret
metadata:
    name: openclaw-public-basic-auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:2VsiO51ERIP4TUXg9cHKy9vVefgELzUeNtnI9WtU4ObLNT4/IVmIpEc8TWe6VkY=,iv:Oij4E34ldgp+S6YdkfYdIodP8Y+7t6hY04JNMDntkTQ=,tag:Bz+oahDIAeRWrucnpwcinA==,type:str]
sops:
    lastmodified: "2026-03-22T04:06:53Z"
    mac: ENC[AES256_GCM,data:FDcDZUc42DhauE3lzkOf3MxV3wrv733QYsbuo9nSj4gWUz+Q+z1VzgPMJ4lld/ctZrrQfJs6rkneQDfPfrHaVJ9xTk3sVkCpyFnTjsBOYL9h/WiJjW9Z7jYDur11vdJhnvtiUN58hLiUUZDNVHYTmR5e5rZ3ZyiKYLR2z//KPyA=,iv:HId2L7CFkbhumJCgHBfTq2/cJ6Csy7FIqxo6dn0VWrI=,tag:Q7H4Wy08zIItqLeCz7g1dg==,type:str]
    pgp:
        - created_at: "2026-03-22T04:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5mBKGEIMocYAQ//ZhJ8QLnj3LX8jrJaZmk0ie6AEBw8VIVWmm64CxZAFQeS
            kiJHeq7Hkf/uHp0E049BswSxflb+4yphaY04DJNqc/uGKT7BWc1lNZZFG5jChIQF
            C3Pb41CgZFA6a0q/3SWiOy9pzzQDWorwnSGsZWY+zo8OwWPvVbbmXaz31eTMTpoh
            1kBDBtryw8wybaw1VluRpzdbAKALtMPt2d6TOkfw+hjgkKzkksrvDtjJTtGCMQoJ
            +J4SxrRps3hYGa+9GMUFlBADgO/UORRz1Oq1KKgzwyL2e7Vdl4bQ+bZLYHWaZyAY
            BuQJmai5POqrv8ifdAkpgpKAPt2CpXd63bImXkWxHlwPknDAKP196gDLH5zTZ2Gn
            VWanpNBS3134e+WIf6/89gJjGITQhsTjBhqZOpdzPHql8PPrP+qfGruDUdHLucku
            lyx9pqAJTW1FtfM0W35DsGgUku8YQmFhZmSrUAmRDVqAWoJEnzcMWdETF/8T0EkV
            Vtpj6exDf8alK4f0HVKnwgV74woJ+Cr6rIEQLr1vuNgN0MD0bcIPQskbbPTM+DhO
            YWLRI4RpEpqADDW4hQ5kecpqn4rx/FaqeXPQ/C5vh7B0ASQqAnU0QP8BnC+eXN/Y
            bAwzWOrRbVyUuBJr7aS9PUSltKTF5ywLGOkF4FH+4ngRewuMepdGEVEJT7EY7xHS
            UQG2JxmYcQ3T6QEssf4bQTF1eB+paIxjbm5aQSlrcd69P4RI8OpZAirh6u51E4Jm
            uyL9E4Ch1IR+eeOD1O+BnHGabUv0l/rvt+9d5OBJS5k9ng==
            =lUaL
            -----END PGP MESSAGE-----
          fp: 85974506EC695392044308059D98CDACFF04FD78
        - created_at: "2026-03-22T04:06:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA0LGYlOQPTf9AQ/9ER3sIIe+f/mLPZhhXwLRgUV2mtU29GBIb8SKEwxfYTud
            9RxqMLELaz5gGtcQIa8BjbadYTS0nlmJMl/rADbEIAKZYVgDUZidIaCLkzGaolBy
            07hepYuTxslZ2z4iRZ7o5jTKRn67KshCKhJlCYn2p1wP/IkTSPfOp70Cazy+5TBj
            8gcUqT3dAxCjGBgaGmgBqYyYI0YHRZhS7h4ieWuxSf6K/A/+M9acVXCOL/hfiGYx
            W325WBiW/746BLkVQCiHmMmk7i4bxteMD2VJbMwIDvkJFewpA6/s5OJFi5NioKtH
            7E9OJ6IWgvjh+bbRY0Hfzmdi64BVkCA7JlvcM1nmw5V/bjrZa6B/GvVedv/nAQXT
            W0kyLPSr0+FjhWqXnpPHQBVQUDP4goovzkWF9h9XyBYhvzUlP4SpTxdd6xUvyWh4
            pGsgvdBEVBFIg5c0VNAoKTYPdf9CvW8CG/6O4VmnxrPC55SRua0DDJSFiOqQEoGd
            h26yt0V7+6mVIHw4sDfbNN7Y47Od/3TRznv9cfgvldyUktBpF1dApNdY7+09dUhZ
            +7wWOpx3TFCLLurvw4D0T7obhEIdGH5Zu8CN3OnrR6rAzgUBWuUZqdVuNk+te01d
            7KQMF4Hs7CqTSCUFc1X6VhtT3/oWb65Cd2VQdJOJ1TBjTGutdZQblK6pjxH99WnS
            UQGvagbhgVpUauPZZz8e0/SwZcBaQl6yuvTCab8ytcLoaohrkxJKoC6EL5Oh2W0R
            kvuDxz371v543izaVk3eIVy4YWL/xjEAs9mt2fiUIJlbzg==
            =b978
            -----END PGP MESSAGE-----
          fp: 2DADB88EC6EA687971F53F10E9936473C592AEDF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
