apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/namespace.yaml
# Snapshot stuff
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/csi-snapshotter?ref=v8.6.0
- https://github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v8.6.0
- https://github.com/kubernetes-csi/external-snapshotter//client/config/crd?ref=v8.6.0
helmCharts:
- name: democratic-csi
  # includeCRDs: true
  releaseName: zfs-local-dataset
  version: 0.15.1
  repo: https://democratic-csi.github.io/charts/
  namespace: democratic-csi
  valuesFile: ./resources/values-zfs-local.yaml
