apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          env:
            - name: REDIS_URL
              $patch: delete

