apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: snapshot-controller
  namespace: democratic-csi
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
