- op: add
  path: /spec/ports/2
  value:
    name: minecraft-alt
    port: 12345
    targetPort: minecraft
    protocol: TCP
- op: add
  path: /spec/ports/3
  value:
    name: bluemap
    port: 8100
    targetPort: bluemap
    protocol: TCP
