apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./resources/volume.yaml
- ./resources/ingress.yaml

namespace: ircclient

configMapGenerator:
- name: thelounge-permissions
  literals: &perms
  - "PUID=1000"
  - "PGID=1000"
  - "TZ=America/Toronto"
- name: znc-permissions
  literals: *perms
- name: thelounge-config
  files:
  - "config.js=./config/thelounge.js"

images:
- name: lscr.io/linuxserver/thelounge
  digest: sha256:276a04a7b203ff121c2440f3f4bdcea2f9a865ba8971b6b2f372e848c789a0f8
- name: lscr.io/linuxserver/znc
  digest: sha256:39a2f84a8376cb71bdb969447cff4e8ffa953ff618f9c5cda9b67b14d3bf6d1d