apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./resources/volume.yaml
- ./resources/ingress.yaml

namespace: ircclient

configMapGenerator:
- name: thelounge-permissions
  literals: &perms
  - "PUID=1000"
  - "PGID=1000"
  - "TZ=America/Toronto"
- name: znc-permissions
  literals: *perms
- name: thelounge-config
  files:
  - "config.js=./config/thelounge.js"

images:
- name: lscr.io/linuxserver/thelounge
  digest: sha256:d8f850ca744bb62319442413c6db93e752a88fc2cb8829f260bc68c9bfce3719
- name: lscr.io/linuxserver/znc
  digest: sha256:d2bceb0d55c84bb053039724787297b9a8ba4f532182d27eabd47d6e88a5a268