apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./resources/volume.yaml
- ./resources/ingress.yaml

namespace: ircclient

configMapGenerator:
- name: thelounge-permissions
  literals: &perms
  - "PUID=1000"
  - "PGID=1000"
  - "TZ=America/Toronto"
- name: znc-permissions
  literals: *perms
- name: thelounge-config
  files:
  - "config.js=./config/thelounge.js"

images:
- name: lscr.io/linuxserver/thelounge
  digest: sha256:a50f0f5e99cd43970c24bb994fc65c8ce12d31c44f882c8ac34dab00a106d1e2
- name: lscr.io/linuxserver/znc
  digest: sha256:6276e50d2ff682fd01f9397a1acdb9a26db7e6176fa63bfedb8b17b26c6d2555