apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: renovate

images:
- name: renovate/renovate
  newTag: "44.65.5"

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: secret-generator
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secrets/renovate-secrets.yaml

configMapGenerator:
- name: renovate-config
  files:
  - ./config/config.json
