apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: renovate

images:
- name: renovate/renovate
  newTag: "43.59.3"

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/renovate-secrets.yaml

configMapGenerator:
- name: renovate-config
  files:
  - ./config/config.json
