apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  storageClassName: truenas-nfs-spitfire-fast
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
