apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./resources/database.yaml
- ./resources/ingress.yaml
- ./resources/monitoring-rbac.yaml

namespace: guacamole

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/guacamole-database.yaml

images:
- name: guacamole/guacamole
  newTag: "1.6.0"
- name: guacamole/guacd
  newTag: "1.6.0"