apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://gitops.305-1700.tdude.co
  repositories: |
    - url: https://git.tdude.co/tristan/infrastructure.git
  repository.credentials: |
    - url: https://git.tdude.co/tristan/infrastructure.git
  oidc.config: |
    name: Pocket ID
    issuer: https://id.305-1700.tdude.co
    clientID: $oidc.pocket-id.clientId
    clientSecret: $oidc.pocket-id.clientSecret
    requestedScopes:
    - openid
    - profile
    - email
    - groups
    - offline_access
    refreshTokenThreshold: 2m
    requestedIDTokenClaims:
      email:
        essential: true
        values:
        - tristan@tdude.co
      groups:
        essential: true
