---
apiVersion: v1
kind: Service
metadata:
  name: windows-vm
spec:
  ports:
  - name: rdp
    port: 3389
    targetPort: 3389
    protocol: TCP
  selector:
    vm.kubevirt.io/name: windows-vm
  type: ClusterIP
