---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-hdd
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  storageClassName: truenas-iscsi-spitfire-fast
  resources:
    requests:
      storage: 100Gi
