# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.1"

ANSIBLE_VERSION = "2.9.*"

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = false
    vb.memory = "4096"

    vb.name = 'bedrock-vagrant'    

    vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

  end

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443

  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.install = true
    ansible.install_mode = "pip_args_only"
    ansible.pip_args = "ansible==#{ANSIBLE_VERSION}"
    ansible.playbook = "sapling-testing.yml"
    ansible.galaxy_role_file = "roles.yml"
    ansible.galaxy_roles_path = "/tmp/galaxy_roles"
  end  

end
