---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-security
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
  oidc:
    provider:
      issuer: "https://id.235.tdude.co"
    clientID: "a9803139-afb5-4e0b-a6e7-63b8d5934b71"
    clientSecret:
      name: "pocket-id-client-secret"
    redirectURL: "https://dummy.235.tdude.co/oauth2/callback"