apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/cloudflare-api-token.yaml

resources:
- ../../base
- ./resources/cluster-issuer.yaml

namespace: cert-manager