nameOverride: "envoy-gateway"
fullnameOverride: "envoy-gateway"

crds:
  envoyGateway:
    enabled: true
  gatewayAPI:
    enabled: true
    channel: "experimental"

config:
  envoyGateway:
    gatewayAPI:
      enabled:
      - ListenerSet