apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
spec:
  ports:
  - name: https-metrics
    port: 10252
    targetPort: 10252
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-controller-manager-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager
    kubernetes.io/service-name: kube-controller-manager-external
addressType: IPv6
ports:
- name: https-metrics
  protocol: TCP
  port: 10252
endpoints:
- addresses:
  - 2a0c:9a46:636:29::5 # sassaflash.235.tdude.co
  conditions:
    ready: true
- addresses:
  - 2a0c:9a46:636:29::6 # stormfeather.235.tdude.co
  conditions:
    ready: true
- addresses:
  - 2a0c:9a46:636:29::7 # soarin.235.tdude.co
  conditions:
    ready: true
---
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
spec:
  ports:
  - name: https-metrics
    port: 10251
    targetPort: 10251
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-scheduler-external
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler
    kubernetes.io/service-name: kube-scheduler-external
addressType: IPv6
ports:
- name: https-metrics
  protocol: TCP
  port: 10251
endpoints:
- addresses:
  - 2a0c:9a46:636:29::5 # sassaflash.235.tdude.co
  conditions:
    ready: true
- addresses:
  - 2a0c:9a46:636:29::6 # stormfeather.235.tdude.co
  conditions:
    ready: true
- addresses:
  - 2a0c:9a46:636:29::7 # soarin.235.tdude.co
  conditions:
    ready: true
