apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/namespace.yaml

namespace: mariadb-operator

helmCharts:
- name: mariadb-operator-crds
  repo: oci://ghcr.io/mariadb-operator/charts
  version: 26.6.0
  releaseName: mariadb-operator-crds
  namespace: mariadb-operator
- name: mariadb-operator
  repo: oci://ghcr.io/mariadb-operator/charts
  version: 26.6.0
  releaseName: mariadb-operator
  namespace: mariadb-operator
  valuesFile: ./resources/values.yaml
