apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: attention-attention

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/discord-token.yaml