apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ./resources/awx.yaml
- ./resources/database.yaml
- ./resources/monitoring-rbac.yaml

namespace: awx

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/awx-credentials.yaml
  - ./secrets/postgres-credentials.yaml
  - ./secrets/awx-admin-password.yaml