apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops-exec
  metadata:
    name: secret-generator
  files:
  - ./secrets/api-keys-secret.yaml

resources:
- ../../base

namespace: claw
